### ISSUE TITLE
Specifying Classification for Elements?

### ISSUE THREAD

**Issue by dhango** [dancingcactus/python-omniture#28] opened 2015-05-13 19:30 UTC
Hi!

Wondering if there was a method specify a particular classification of an evar and query with that parameter?  https://marketing.adobe.com/developer/documentation/omniture-administration/r-getclassifications

The Omniture API for R seems to have an option for that i.e. QueueRanked(suite, date.from, date.to, metrics, elements, classification). Wonder if it is also available in yours?

Thanks!!!

**Comment by dhango** [comment] 2015-05-13 19:41
Nevermind. Found the answer in your elements documentation. Thanks anyway!

**Comment by dancingcactus** [comment] 2015-05-13 20:05
@dhango No problem. Glad you found it.

**Comment by dhango** [comment] 2015-05-13 22:59
So, I am looking to cut a metric by 2+ classifications and it is not clear from the documentation if this is possible. I've tried specifying the value for the classification variable as a list and adding another element line with the other classification that I want to cut by; however, the query seems to only return one cut. Any ideas?

**Comment by aarontoledo** [comment] 2016-07-18 23:58
I am also running into this same issue. From what I'm seeing in query.py, element() sees the correct incoming element and kwargs values, but when this line is executed

element = self._serialize_value(element, 'elements')

multiple classifications on the same eVar end up overwriting. As it steps into _serialize_value() and _normalize_value() things still look good, but when .serialize() gets called, that's where I see the issue occur.

I'm trying to debug it but I haven't found a solution yet.

**Comment by dancingcactus** [comment] 2016-07-19 19:41
I spent some time looking at this and it turns out the data is requested (e.g. `print report`) it correct and it comes back correctly (e.g. `print data`) however it isn't getting processed into the report object correctly. I am still not sure how to fix it but I think the problem is in the `parser_rows` function.

**Comment by aarontoledo** [comment] 2016-07-20 23:09
I dug into this more. Here's an example of when I try to break down an eVar with it's own classification. Within elements[] it looks like its duplicating the breakdown

Example:
query = suite.report.element('evar7',top=100).element('evar7',top=100,classification='Campaign Name').metrics('instances').range(start=start.strftime('%Y-%m-%d'), stop=end.strftime('%Y-%m-%d'),months=0,days=0,granularity='month')

Print of query:
{
    "reportDescription": {
        "elements": [
            {
                "top": 100,
                "id": "evar7",
                "classification": "Campaign Name"
            },
            {
                "top": 100,
                "id": "evar7",
                "classification": "Campaign Name"
            }
        ],
        "dateGranularity": "month",
        "dateTo": "2015-01-31",
        "dateFrom": "2015-01-01",
        "metrics": [
            {
                "id": "instances"
            }
        ],
        "reportSuiteID": "ABC123"
    }
}

My expectation is that query should return this, which I was able to validate in API Explorer:
{
    "reportDescription": {
        "elements": [
            {
                "top": 100,
                "id": "evar7"
            },
            {
                "top": 100,
                "id": "evar7",
                "classification": "Campaign Name"
            }
        ],
        "dateGranularity": "month",
        "dateTo": "2015-01-31",
        "dateFrom": "2015-01-01",
        "metrics": [
            {
                "id": "instances"
            }
        ],
        "reportSuiteID": "ABC123"
    }
}

**Comment by dancingcactus** [comment] 2016-07-21 16:00
@dhango thanks for that. I had missed that is was just repeating the same classification. I think I found the problem. I am just running it through all the automated tests to make sure I didn't break anything else in the process. It ended up being a problem where the object that we used for an element was just being referenced instead of copied so when you had a classification of the same element it would update the object instead of making a new one.

**Comment by aarontoledo** [comment] 2016-07-22 01:12
Having issues pushing changes right now, but here's how I got around the `parser_rows` issue.

**Replaced this**
```
elif self.type == "trended":
	element = str(self.elements[level-1].id)
```

**With this**
```
elif self.type == "trended":
    if hasattr(self.elements[level-1], 'classification'):
        element = str(self.elements[level-1].id) + ' | ' + str(self.elements[level-1].classification).encode('utf-8')
    else:
        element = str(self.elements[level-1].id)
```	

which will concatenate the ID with the Classification, separated with a pipe and storing it as a separate property for that row of data

**Comment by dancingcactus** [comment] 2016-07-22 05:59
@aarontoledo Perfect. Thanks for looking at that. I am prepping a pull requests with the changes. I will send it over to you as soon as it is ready. This one is a tricky one to write unit tests for :-)

**Comment by dancingcactus** [comment] 2016-07-22 06:28
@aarontoledo Have a look at the pull request and let me know what you think.

**Comment by aarontoledo** [comment] 2016-07-22 15:33
@dancingcactus Looks good to me!

**Comment by dancingcactus** [comment] 2016-07-23 01:32
Sounds good. The branch has been merged.

**Comment by dancingcactus** [comment] 2016-08-19 20:54
Found a new problem when there are mixed classifications. Now the library fails if there is a single classification broken down by a regular dimension.

**Comment by aarontoledo** [comment] 2016-08-19 21:43
I just tried a couple tests and couldn't reproduce the error. Can you provide an example query?

**Comment by dancingcactus** [comment] 2016-08-19 21:55
I was running into problems with something like this. I think I have a fix for it.  I will commit it to a branch so we can look at it. Let me know if you can't reproduce the error. 

```python 
reportSuite.report.elements("evar3", classification = "classification 1").elements("evar5").metric("pageviews").run()
```

**Closed** 2016-08-24 19:36 UTC
Labels: bug
